version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
  server:
    build: .
    image: echo-sample
    ports:
    - "1323:1323"
    volumes:
    - ./:/go/src/github.com/furiko/echo-sample